## Feature Extraction

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'marvel_characters_dataset.csv')
df

,Character,Real Name,Affiliation,Powers,Role,Power Level
0,iron man,Tony Stark,Avengers,"Powered Armor, Genius-level intellect",Hero,Low
1,captain america,Steve Rogers,Avengers,"Super Soldier, Enhanced strength",Hero,Low
2,thor,Thor Odinson,Avengers,"God of Thunder, Weather manipulation",Hero,Low
3,black widow,Natasha Romanoff,Avengers,"Superhuman strength, Espionage",Hero,Low
4,hulk,Bruce Banner,Avengers,"Superhuman strength, Gamma Radiation",Hero,Low
5,spider-man,Peter Parker,Avengers,"Spider sense, Wall crawling",Hero,Low
6,wolverine,James Howlett,X-Men,"Regeneration, Adamantium claws",Hero,Low
7,deadpool,Wade Wilson,X-Force,"Regeneration, Skilled hand-to-hand combatant",Antihero,Low
8,black panther,T’Challa,Avengers,"Superhuman strength, Vibranium suit",Hero,Low
9,doctor strange,Stephen Strange,Avengers,"Sorcery, Magic",Hero,Low
10,ant-man,Scott Lang,Avengers,"Size manipulation, Ant communication",Hero,Low
11,scarlet witch,Wanda Maximoff,Avengers,"Telekinesis, Reality warping",Hero,Low
12,vision,Victor Von Doom,Avengers,"Genius intellect, Magic",Hero,Low
13,daredevil,Matt Murdock,Defenders,"Enhanced senses, Superhuman strength",Hero,Low
14,luke cage,Carl Lucas,Defenders,"Superhuman strength, Bulletproof skin",Hero,Low
15,gamora,Gamora Zenwhoberi,Guardians of the Galaxy,"Superhuman strength, Expert fighter",Hero,Low
16,star-lord,Peter Quill,Guardians of the Galaxy,"Weapons expert, Green energy manipulation",Hero,Low
17,rocket raccoon,Rocket,Guardians of the Galaxy,Cybernetic enhancements,Hero,Low
18,black widow,Natasha Romanoff,Avengers,"Rocket science, Genius intellect",Hero,Low
19,thanos,Thanos,Villain,"Expert marksmanship, Advanced technology",Villain,Low
20,doctor doom,Victor Von Doom,Villain,"Superhuman strength, Regeneration",Villain,Low
21,green goblin,Norman Osborn,Villain,Magical powers,Villain,Low
22,loki,Loki Laufeyson,Avengers,"Superhuman speed, Enhanced senses",Hero,Low
23,hawkeye,Clint Barton,Avengers,"Aerial combat, Shield mastery",Hero,Low
24,bucky barnes,James Buchanan Barnes,Avengers,"Superhuman strength, Regeneration",Hero,Low
25,falcon,Sam Wilson,Avengers,"Chi manipulation, Martial arts expert",Hero,Low
26,shang-chi,Shang-Chi,Avengers,"Skilled combatant, Weapon mastery",Hero,Low
27,moon knight,Marc Spector,Avengers,"Energy manipulation, Expert marksman",Hero,Low
28,elektra,Elektra Natchios,Defenders,"Skilled combatant, Enhanced reflexes",Hero,Low
29,mantis,Mantis,Avengers,"Superhuman strength, Agility",Hero,Low
30,valkyrie,Brunnhilde,Defenders,"Superhuman intelligence, Tentacle control",Hero,Low
31,black bolt,Blackagar Boltagon,Avengers,"Illusion creation, Hypnosis",Hero,Low
32,silver surfer,Norrin Radd,Inhumans,"Superhuman strength, Durability",Hero,Low
33,red skull,Johann Schmidt,Fantastic Four,"Symbiote bonding, Enhanced strength",Villain,Low
34,ultron,Henry Pym,Hydra,"Flight, Superhuman strength, Cosmic energy",Villain,Low
35,hela,Sue Storm,Avengers,Magical powers,Villain,Low
36,mister fantastic,Johnny Storm,Fantastic Four,"Elasticity, Superhuman strength",Hero,Low
37,invisible woman,Ben Grimm,Fantastic Four,"Invisibility, Force field generation",Hero,Low
38,human torch,Otto Octavius,Fantastic Four,"Pyrokinesis, Flight",Hero,Low
39,thing,Quentin Beck,Sinister Six,"Superhuman strength, Durability",Hero,Low
40,doctor octopus,Mac Gargan,Sinister Six,"Superhuman strength, Tentacle control",Hero,Low
41,mysterio,Eddie Brock,Sinister Six,"Illusion creation, Hypnosis",Villain,Low
42,rhino,Carol Danvers,Sinister Six,"Superhuman strength, Durability",Villain,Low
43,venom,Eddie Brock,Avengers,"Symbiote bonding, Enhanced strength",Antihero,Low
44,captain marvel,Carol Danvers,Avengers,"Flight, Superhuman strength, Cosmic energy",Hero,Low

In [3]:
df.head() #Print top 5 rows

,Character,Real Name,Affiliation,Powers,Role,Power Level
0,iron man,Tony Stark,Avengers,"Powered Armor, Genius-level intellect",Hero,Low
1,captain america,Steve Rogers,Avengers,"Super Soldier, Enhanced strength",Hero,Low
2,thor,Thor Odinson,Avengers,"God of Thunder, Weather manipulation",Hero,Low
3,black widow,Natasha Romanoff,Avengers,"Superhuman strength, Espionage",Hero,Low
4,hulk,Bruce Banner,Avengers,"Superhuman strength, Gamma Radiation",Hero,Low

In [4]:
df.head(10) # First 10 rows

,Character,Real Name,Affiliation,Powers,Role,Power Level
0,iron man,Tony Stark,Avengers,"Powered Armor, Genius-level intellect",Hero,Low
1,captain america,Steve Rogers,Avengers,"Super Soldier, Enhanced strength",Hero,Low
2,thor,Thor Odinson,Avengers,"God of Thunder, Weather manipulation",Hero,Low
3,black widow,Natasha Romanoff,Avengers,"Superhuman strength, Espionage",Hero,Low
4,hulk,Bruce Banner,Avengers,"Superhuman strength, Gamma Radiation",Hero,Low
5,spider-man,Peter Parker,Avengers,"Spider sense, Wall crawling",Hero,Low
6,wolverine,James Howlett,X-Men,"Regeneration, Adamantium claws",Hero,Low
7,deadpool,Wade Wilson,X-Force,"Regeneration, Skilled hand-to-hand combatant",Antihero,Low
8,black panther,T’Challa,Avengers,"Superhuman strength, Vibranium suit",Hero,Low
9,doctor strange,Stephen Strange,Avengers,"Sorcery, Magic",Hero,Low

# Make a new column for First_Name and Last_name from Real Name

In [5]:
df["Real Name"].head()

0          Tony Stark
1        Steve Rogers
2        Thor Odinson
3    Natasha Romanoff
4        Bruce Banner
Name: Real Name, dtype: str

In [6]:
#Extract First Name
df["First_Name"] = df["Real Name"].str.split().str[0]
df[["Real Name", "First_Name"]]

                Real Name  First_Name
0              Tony Stark        Tony
1            Steve Rogers       Steve
2            Thor Odinson        Thor
3        Natasha Romanoff     Natasha
4            Bruce Banner       Bruce
5            Peter Parker       Peter
6           James Howlett       James
7             Wade Wilson        Wade
8                T’Challa    T’Challa
9         Stephen Strange     Stephen
10             Scott Lang       Scott
11         Wanda Maximoff       Wanda
12        Victor Von Doom      Victor
13           Matt Murdock        Matt
14             Carl Lucas        Carl
15      Gamora Zenwhoberi      Gamora
16            Peter Quill       Peter
17                 Rocket      Rocket
18       Natasha Romanoff     Natasha
19                 Thanos      Thanos
20        Victor Von Doom      Victor
21          Norman Osborn      Norman
22         Loki Laufeyson        Loki
23           Clint Barton       Clint
24  James Buchanan Barnes       James
25             Sam Wilson         Sam
26              Shang-Chi   Shang-Chi
27           Marc Spector        Marc
28       Elektra Natchios     Elektra
29                 Mantis      Mantis
30             Brunnhilde  Brunnhilde
31     Blackagar Boltagon   Blackagar
32            Norrin Radd      Norrin
33         Johann Schmidt      Johann
34              Henry Pym       Henry
35              Sue Storm         Sue
36           Johnny Storm      Johnny
37              Ben Grimm         Ben
38          Otto Octavius        Otto
39           Quentin Beck     Quentin
40             Mac Gargan         Mac
41            Eddie Brock       Eddie
42          Carol Danvers       Carol
43            Eddie Brock       Eddie
44          Carol Danvers       Carol

In [7]:
#Extract Last Name
df["Last_Name"] = df["Real Name"].str.split().str[-1]
df[["Real Name", "First_Name", "Last_Name"]]

                Real Name  First_Name   Last_Name
0              Tony Stark        Tony       Stark
1            Steve Rogers       Steve      Rogers
2            Thor Odinson        Thor     Odinson
3        Natasha Romanoff     Natasha    Romanoff
4            Bruce Banner       Bruce      Banner
5            Peter Parker       Peter      Parker
6           James Howlett       James     Howlett
7             Wade Wilson        Wade      Wilson
8                T’Challa    T’Challa    T’Challa
9         Stephen Strange     Stephen     Strange
10             Scott Lang       Scott        Lang
11         Wanda Maximoff       Wanda    Maximoff
12        Victor Von Doom      Victor        Doom
13           Matt Murdock        Matt     Murdock
14             Carl Lucas        Carl       Lucas
15      Gamora Zenwhoberi      Gamora  Zenwhoberi
16            Peter Quill       Peter       Quill
17                 Rocket      Rocket      Rocket
18       Natasha Romanoff     Natasha    Romanoff
19                 Thanos      Thanos      Thanos
20        Victor Von Doom      Victor        Doom
21          Norman Osborn      Norman      Osborn
22         Loki Laufeyson        Loki   Laufeyson
23           Clint Barton       Clint      Barton
24  James Buchanan Barnes       James      Barnes
25             Sam Wilson         Sam      Wilson
26              Shang-Chi   Shang-Chi   Shang-Chi
27           Marc Spector        Marc     Spector
28       Elektra Natchios     Elektra    Natchios
29                 Mantis      Mantis      Mantis
30             Brunnhilde  Brunnhilde  Brunnhilde
31     Blackagar Boltagon   Blackagar    Boltagon
32            Norrin Radd      Norrin        Radd
33         Johann Schmidt      Johann     Schmidt
34              Henry Pym       Henry         Pym
35              Sue Storm         Sue       Storm
36           Johnny Storm      Johnny       Storm
37              Ben Grimm         Ben       Grimm
38          Otto Octavius        Otto    Octavius
39           Quentin Beck     Quentin        Beck
40             Mac Gargan         Mac      Gargan
41            Eddie Brock       Eddie       Brock
42          Carol Danvers       Carol     Danvers
43            Eddie Brock       Eddie       Brock
44          Carol Danvers       Carol     Danvers

In [8]:
# Function for character count
def char_leng(character):
    count = 0
    for i in character:
        count += 1
    return count

In [24]:
df["Char_Length"] = df["Character"].apply(char_leng)
df[["Character","Char_Length"]]

           Character  Char_Length
0           iron man            8
1    captain america           15
2               thor            4
3        black widow           11
4               hulk            4
5         spider-man           10
6          wolverine            9
7           deadpool            8
8      black panther           13
9     doctor strange           14
10           ant-man            7
11     scarlet witch           13
12            vision            6
13         daredevil            9
14         luke cage            9
15            gamora            6
16         star-lord            9
17    rocket raccoon           14
18       black widow           11
19            thanos            6
20       doctor doom           11
21      green goblin           12
22              loki            4
23           hawkeye            7
24      bucky barnes           12
25            falcon            6
26         shang-chi            9
27       moon knight           11
28           elektra            7
29            mantis            6
30          valkyrie            8
31        black bolt           10
32     silver surfer           13
33         red skull            9
34            ultron            6
35              hela            4
36  mister fantastic           16
37   invisible woman           15
38       human torch           11
39             thing            5
40    doctor octopus           14
41          mysterio            8
42             rhino            5
43             venom            5
44    captain marvel           14

In [10]:
df.head(10)

,Character,Real Name,Affiliation,Powers,Role,Power Level,First_Name,Last_Name,Char_Length
0,iron man,Tony Stark,Avengers,"Powered Armor, Genius-level intellect",Hero,Low,Tony,Stark,8
1,captain america,Steve Rogers,Avengers,"Super Soldier, Enhanced strength",Hero,Low,Steve,Rogers,15
2,thor,Thor Odinson,Avengers,"God of Thunder, Weather manipulation",Hero,Low,Thor,Odinson,4
3,black widow,Natasha Romanoff,Avengers,"Superhuman strength, Espionage",Hero,Low,Natasha,Romanoff,11
4,hulk,Bruce Banner,Avengers,"Superhuman strength, Gamma Radiation",Hero,Low,Bruce,Banner,4
5,spider-man,Peter Parker,Avengers,"Spider sense, Wall crawling",Hero,Low,Peter,Parker,10
6,wolverine,James Howlett,X-Men,"Regeneration, Adamantium claws",Hero,Low,James,Howlett,9
7,deadpool,Wade Wilson,X-Force,"Regeneration, Skilled hand-to-hand combatant",Antihero,Low,Wade,Wilson,8
8,black panther,T’Challa,Avengers,"Superhuman strength, Vibranium suit",Hero,Low,T’Challa,T’Challa,13
9,doctor strange,Stephen Strange,Avengers,"Sorcery, Magic",Hero,Low,Stephen,Strange,14

In [11]:
# Real Name word count
def count_words(name):
    return(len(name.split()))

In [23]:
df["Word_Count"] = df["Real Name"].apply(count_words)
df[["Real Name", "Word_Count"]]

                Real Name  Word_Count
0              Tony Stark           2
1            Steve Rogers           2
2            Thor Odinson           2
3        Natasha Romanoff           2
4            Bruce Banner           2
5            Peter Parker           2
6           James Howlett           2
7             Wade Wilson           2
8                T’Challa           1
9         Stephen Strange           2
10             Scott Lang           2
11         Wanda Maximoff           2
12        Victor Von Doom           3
13           Matt Murdock           2
14             Carl Lucas           2
15      Gamora Zenwhoberi           2
16            Peter Quill           2
17                 Rocket           1
18       Natasha Romanoff           2
19                 Thanos           1
20        Victor Von Doom           3
21          Norman Osborn           2
22         Loki Laufeyson           2
23           Clint Barton           2
24  James Buchanan Barnes           3
25             Sam Wilson           2
26              Shang-Chi           1
27           Marc Spector           2
28       Elektra Natchios           2
29                 Mantis           1
30             Brunnhilde           1
31     Blackagar Boltagon           2
32            Norrin Radd           2
33         Johann Schmidt           2
34              Henry Pym           2
35              Sue Storm           2
36           Johnny Storm           2
37              Ben Grimm           2
38          Otto Octavius           2
39           Quentin Beck           2
40             Mac Gargan           2
41            Eddie Brock           2
42          Carol Danvers           2
43            Eddie Brock           2
44          Carol Danvers           2

In [25]:
# Encoding Role with 0 and 1
def encoded_role(role):
    if role == "Hero":
        return 2
    elif role == "Villain":
        return 0
    elif role == "Antihero":
        return 1

In [26]:
df["Encode_Role"] = df["Role"].apply(encoded_role)
df[["Role", "Encode_Role"]]

        Role  Encode_Role
0       Hero            2
1       Hero            2
2       Hero            2
3       Hero            2
4       Hero            2
5       Hero            2
6       Hero            2
7   Antihero            1
8       Hero            2
9       Hero            2
10      Hero            2
11      Hero            2
12      Hero            2
13      Hero            2
14      Hero            2
15      Hero            2
16      Hero            2
17      Hero            2
18      Hero            2
19   Villain            0
20   Villain            0
21   Villain            0
22      Hero            2
23      Hero            2
24      Hero            2
25      Hero            2
26      Hero            2
27      Hero            2
28      Hero            2
29      Hero            2
30      Hero            2
31      Hero            2
32      Hero            2
33   Villain            0
34   Villain            0
35   Villain            0
36      Hero            2
37      Hero            2
38      Hero            2
39      Hero            2
40      Hero            2
41   Villain            0
42   Villain            0
43  Antihero            1
44      Hero            2

In [27]:
# Power level encoding
def encoding_power(power):
    if power == "Low":
        return 0
    elif power == "Medium":
        return 1
    elif power == "High":
        return 2

In [29]:
df["Encoded_Power"] = df["Power Level"].apply(encoding_power)
df[["Power Level", "Encoded_Power"]]

   Power Level  Encoded_Power
0          Low              0
1          Low              0
2          Low              0
3          Low              0
4          Low              0
5          Low              0
6          Low              0
7          Low              0
8          Low              0
9          Low              0
10         Low              0
11         Low              0
12         Low              0
13         Low              0
14         Low              0
15         Low              0
16         Low              0
17         Low              0
18         Low              0
19         Low              0
20         Low              0
21         Low              0
22         Low              0
23         Low              0
24         Low              0
25         Low              0
26         Low              0
27         Low              0
28         Low              0
29         Low              0
30         Low              0
31         Low              0
32         Low              0
33         Low              0
34         Low              0
35         Low              0
36         Low              0
37         Low              0
38         Low              0
39         Low              0
40         Low              0
41         Low              0
42         Low              0
43         Low              0
44         Low              0

In [30]:
# Count Powers
def count_powers(power):
    return len(power.split(","))

In [33]:
df["Count_Powers"] = df["Powers"].apply(count_powers)
df[["Powers", "Count_Powers"]]

                                          Powers  Count_Powers
0          Powered Armor, Genius-level intellect             2
1               Super Soldier, Enhanced strength             2
2           God of Thunder, Weather manipulation             2
3                 Superhuman strength, Espionage             2
4           Superhuman strength, Gamma Radiation             2
5                    Spider sense, Wall crawling             2
6                 Regeneration, Adamantium claws             2
7   Regeneration, Skilled hand-to-hand combatant             2
8            Superhuman strength, Vibranium suit             2
9                                 Sorcery, Magic             2
10          Size manipulation, Ant communication             2
11                  Telekinesis, Reality warping             2
12                       Genius intellect, Magic             2
13          Enhanced senses, Superhuman strength             2
14         Superhuman strength, Bulletproof skin             2
15           Superhuman strength, Expert fighter             2
16     Weapons expert, Green energy manipulation             2
17                       Cybernetic enhancements             1
18              Rocket science, Genius intellect             2
19      Expert marksmanship, Advanced technology             2
20             Superhuman strength, Regeneration             2
21                                Magical powers             1
22             Superhuman speed, Enhanced senses             2
23                 Aerial combat, Shield mastery             2
24             Superhuman strength, Regeneration             2
25         Chi manipulation, Martial arts expert             2
26             Skilled combatant, Weapon mastery             2
27          Energy manipulation, Expert marksman             2
28          Skilled combatant, Enhanced reflexes             2
29                  Superhuman strength, Agility             2
30     Superhuman intelligence, Tentacle control             2
31                   Illusion creation, Hypnosis             2
32               Superhuman strength, Durability             2
33           Symbiote bonding, Enhanced strength             2
34    Flight, Superhuman strength, Cosmic energy             3
35                                Magical powers             1
36               Elasticity, Superhuman strength             2
37          Invisibility, Force field generation             2
38                           Pyrokinesis, Flight             2
39               Superhuman strength, Durability             2
40         Superhuman strength, Tentacle control             2
41                   Illusion creation, Hypnosis             2
42               Superhuman strength, Durability             2
43           Symbiote bonding, Enhanced strength             2
44    Flight, Superhuman strength, Cosmic energy             3

In [34]:
df.head(10)

,Character,Real Name,Affiliation,Powers,Role,Power Level,First_Name,Last_Name,Char_Length,Word_Count,Encode_Role,Encoded_Power,Count_Powers
0,iron man,Tony Stark,Avengers,"Powered Armor, Genius-level intellect",Hero,Low,Tony,Stark,8,2,2,0,2
1,captain america,Steve Rogers,Avengers,"Super Soldier, Enhanced strength",Hero,Low,Steve,Rogers,15,2,2,0,2
2,thor,Thor Odinson,Avengers,"God of Thunder, Weather manipulation",Hero,Low,Thor,Odinson,4,2,2,0,2
3,black widow,Natasha Romanoff,Avengers,"Superhuman strength, Espionage",Hero,Low,Natasha,Romanoff,11,2,2,0,2
4,hulk,Bruce Banner,Avengers,"Superhuman strength, Gamma Radiation",Hero,Low,Bruce,Banner,4,2,2,0,2
5,spider-man,Peter Parker,Avengers,"Spider sense, Wall crawling",Hero,Low,Peter,Parker,10,2,2,0,2
6,wolverine,James Howlett,X-Men,"Regeneration, Adamantium claws",Hero,Low,James,Howlett,9,2,2,0,2
7,deadpool,Wade Wilson,X-Force,"Regeneration, Skilled hand-to-hand combatant",Antihero,Low,Wade,Wilson,8,2,1,0,2
8,black panther,T’Challa,Avengers,"Superhuman strength, Vibranium suit",Hero,Low,T’Challa,T’Challa,13,1,2,0,2
9,doctor strange,Stephen Strange,Avengers,"Sorcery, Magic",Hero,Low,Stephen,Strange,14,2,2,0,2