## Merging Joining Concatination

In [1]:
import numpy as np
import pandas as pd

In [ ]:
# Merging Two data frames
employees = pd.DataFrame({ # employee information
    'emp_Id' : [1, 2, 3, 4, 5],
    'name': ['Anna', 'Peter', 'Bob', 'Jack', 'Oggy'],
    'dept': ["HR", 'IT', 'Finance', 'IT', 'HR']
})

salaries = pd.DataFrame({ # salary information
   'emp_Id' : [1, 2, 3, 6, 7],
   'salary': [60000, 70000, 65000, 80000, 65000],
   'bonus': [5000, 2000, 4000, 3000, 1500] 
})

In [3]:
employees

   emp_Id   name     dept
0       1   Anna       HR
1       2  Peter       IT
2       3    Bob  Finance
3       4   Jack       IT
4       5   Oggy       HR

In [4]:
salaries

   emp_Id  salary  bonus
0       1   60000   5000
1       2   70000   2000
2       3   65000   4000
3       6   80000   3000
4       7   65000   1500

In [ ]:
pd.merge(employees, salaries) # Merge only common keys like employee_Id

   emp_Id   name     dept  salary  bonus
0       1   Anna       HR   60000   5000
1       2  Peter       IT   70000   2000
2       3    Bob  Finance   65000   4000

In [6]:
pd.merge(employees, salaries, on='emp_Id', how='inner')

   emp_Id   name     dept  salary  bonus
0       1   Anna       HR   60000   5000
1       2  Peter       IT   70000   2000
2       3    Bob  Finance   65000   4000

In [7]:
pd.merge(employees, salaries, on='emp_Id', how='outer')

   emp_Id   name     dept   salary   bonus
0       1   Anna       HR  60000.0  5000.0
1       2  Peter       IT  70000.0  2000.0
2       3    Bob  Finance  65000.0  4000.0
3       4   Jack       IT      NaN     NaN
4       5   Oggy       HR      NaN     NaN
5       6    NaN      NaN  80000.0  3000.0
6       7    NaN      NaN  65000.0  1500.0

In [ ]:
pd.merge(employees, salaries, on='emp_Id', how='left') # Do operation on employees basis

   emp_Id   name     dept   salary   bonus
0       1   Anna       HR  60000.0  5000.0
1       2  Peter       IT  70000.0  2000.0
2       3    Bob  Finance  65000.0  4000.0
3       4   Jack       IT      NaN     NaN
4       5   Oggy       HR      NaN     NaN

In [ ]:
pd.merge(employees, salaries, on='emp_Id', how='right') # Do operation on salaries basis

   emp_Id   name     dept  salary  bonus
0       1   Anna       HR   60000   5000
1       2  Peter       IT   70000   2000
2       3    Bob  Finance   65000   4000
3       6    NaN      NaN   80000   3000
4       7    NaN      NaN   65000   1500

## Concatination of two Data Frames

In [11]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [12]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [13]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
# Concate df1, df2
pd.concat([df1, df2]) # column-wise

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [15]:
pd.concat([df1, df2], axis=1) # row-wise

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

## Joining of Two Data Frames

In [20]:
df1 = pd.DataFrame({
    'Name': ["Alice", "Bob", 'Jack']
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    'Score': [88, 90, 89]
}, index=[2, 3, 4])

In [17]:
df1

    Name
1  Alice
2    Bob
3   Jack

In [21]:
df2

   Score
2     88
3     90
4     89

In [22]:
df1.join(df2)

    Name  Score
1  Alice    NaN
2    Bob   88.0
3   Jack   90.0

In [23]:
df1.join(df2, how='outer')

    Name  Score
1  Alice    NaN
2    Bob   88.0
3   Jack   90.0
4    NaN   89.0