## DataFrames in Pandas

In [1]:
import numpy as np
import pandas as pd

In [34]:
# Creating dataFrames using dictionary with keys
data_dic = {
    "Name": ["Rit", "Soumo", "Tukai"],
    "Age": [25, 26, 24],
    "City": ["Mekhliganj", "Jalpaiguri", "Siliguri"],
    "Salary": [40000, 50000, 30000]
}

df = pd.DataFrame(data_dic)

# Creating dataFrames using list without keys
data_list = [
    ["Rit", 25, "Mekhliganj", 40000],
    ["Soumo", 26, "Jalpaiguri", 50000],
    ["Tukai", 24, "Siliguri", 30000],
]

df2 = pd.DataFrame(data_list)

# Insert keys into existing dataframes
keys = ["Name", "Age", "City", "Salary"]

df3 = pd.DataFrame(data_list, columns=keys)

In [57]:
df

    Name  Age        City  Salary Occupation
0    Rit   25  Mekhliganj   40000      Engg.
1  Soumo   26  Jalpaiguri   50000       Doc.
2  Tukai   24    Siliguri   30000     Lawyer

In [36]:
df2

       0   1           2      3
0    Rit  25  Mekhliganj  40000
1  Soumo  26  Jalpaiguri  50000
2  Tukai  24    Siliguri  30000

In [35]:
df3

    Name  Age        City  Salary
0    Rit   25  Mekhliganj   40000
1  Soumo   26  Jalpaiguri   50000
2  Tukai   24    Siliguri   30000

## Selection and Indexing of columns

In [41]:
# Selection of columns
df["Name"] #select one column

0      Rit
1    Soumo
2    Tukai
Name: Name, dtype: str

In [42]:
# select multiple columns
df[["Name", "Salary"]]

    Name  Salary
0    Rit   40000
1  Soumo   50000
2  Tukai   30000

In [63]:
# Creating a new column into existing Dataframes
df["Occupation"] = ["Engg.", "Doc.", "Lawyer"]
df

    Name  Age        City  Salary Occupation
0    Rit   25  Mekhliganj   40000      Engg.
1  Soumo   26  Jalpaiguri   50000       Doc.
2  Tukai   24    Siliguri   30000     Lawyer

## Removing a Column

In [64]:
# Drop a columns
df.drop('Occupation', axis=1) # Its only show copy of actual data, do not drop the column from RAM. If want to drop column from RAM, use 'inplace=true'

    Name  Age        City  Salary
0    Rit   25  Mekhliganj   40000
1  Soumo   26  Jalpaiguri   50000
2  Tukai   24    Siliguri   30000

In [65]:
df.drop('Occupation', axis=1, inplace=True) # Drop column permanently
df

    Name  Age        City  Salary
0    Rit   25  Mekhliganj   40000
1  Soumo   26  Jalpaiguri   50000
2  Tukai   24    Siliguri   30000

In [66]:
# Drop multiple Columns
df.drop(["City", "Salary"], axis=1)

    Name  Age
0    Rit   25
1  Soumo   26
2  Tukai   24

In [ ]:
# Drop Row
df.drop(0) #It always choose axis=0

    Name  Age        City  Salary
1  Soumo   26  Jalpaiguri   50000
2  Tukai   24    Siliguri   30000

## Selecting Rows

In [ ]:
# Select a row location
df.loc[0]

Name             Rit
Age               25
City      Mekhliganj
Salary         40000
Name: 0, dtype: object

In [71]:
# Select multiple row location
df.loc[[0, 1]]

    Name  Age        City  Salary
0    Rit   25  Mekhliganj   40000
1  Soumo   26  Jalpaiguri   50000

In [ ]:
# Select a perticular rows of column
df.loc[[0, 1],["City", "Salary"]]

         City  Salary
0  Mekhliganj   40000
1  Jalpaiguri   50000

## Conditional Operation

In [ ]:
# Select people whose age is above 24
df[df["Age"] > 24] # Use only one condition

    Name  Age        City  Salary
0    Rit   25  Mekhliganj   40000
1  Soumo   26  Jalpaiguri   50000

In [ ]:
# Use multiple condition
df[(df["Age"] > 24) & (df["Salary"] == 50000)]

    Name  Age        City  Salary
1  Soumo   26  Jalpaiguri   50000