## Finding Missing Data

In [1]:
import numpy as np
import pandas as pd

In [16]:
# Find NaN values from a list
data = {
    "A": [1, np.nan, 2, 3],
    "B": [2, 3, 5, np.nan],
    "C": [4, np.nan, 7, np.nan],
    "D": [5, 8, np.nan, np.nan]
}

df = pd.DataFrame(data)

In [17]:
df

     A    B    C    D
0  1.0  2.0  4.0  5.0
1  NaN  3.0  NaN  8.0
2  2.0  5.0  7.0  NaN
3  3.0  NaN  NaN  NaN

In [18]:
df.isna()

       A      B      C      D
0  False  False  False  False
1   True  False   True  False
2  False  False  False   True
3  False   True   True   True

In [19]:
# Count NaN
df.isna().sum()

A    1
B    1
C    2
D    2
dtype: int64

## Removing Missing Data

In [20]:
df

     A    B    C    D
0  1.0  2.0  4.0  5.0
1  NaN  3.0  NaN  8.0
2  2.0  5.0  7.0  NaN
3  3.0  NaN  NaN  NaN

In [ ]:
#Removing only NaN value rows  
df.dropna()

     A    B    C    D
0  1.0  2.0  4.0  5.0

In [25]:
df.dropna(thresh=3)

     A    B    C    D
0  1.0  2.0  4.0  5.0
2  2.0  5.0  7.0  NaN

In [24]:
df.dropna().any()

A    True
B    True
C    True
D    True
dtype: bool

## Fill Missing values

In [26]:
df

     A    B    C    D
0  1.0  2.0  4.0  5.0
1  NaN  3.0  NaN  8.0
2  2.0  5.0  7.0  NaN
3  3.0  NaN  NaN  NaN

In [ ]:
df.fillna(0) # Fill 0 all the NaN values

     A    B    C    D
0  1.0  2.0  4.0  5.0
1  0.0  3.0  0.0  8.0
2  2.0  5.0  7.0  0.0
3  3.0  0.0  0.0  0.0

In [29]:
# Fill specific values to the column wise
val = {"A":10, "B": 20, "C": 30, "D": 40}
df.fillna(val)

      A     B     C     D
0   1.0   2.0   4.0   5.0
1  10.0   3.0  30.0   8.0
2   2.0   5.0   7.0  40.0
3   3.0  20.0  30.0  40.0