## Pivot Tables

In [1]:
import numpy as np
import pandas as pd

In [4]:
data = {
    "Date": [
        "2026-01-05", "2026-01-12", "2026-01-18",
        "2026-02-03", "2026-02-10", "2026-02-17",
        "2026-03-02", "2026-03-09", "2026-03-16",
        "2026-04-04", "2026-04-11", "2026-04-18",
        "2026-05-06", "2026-05-13", "2026-05-20"
    ],
    "Product": [
        "Laptop", "Mobile", "Tablet",
        "Laptop", "Mobile", "Tablet",
        "Laptop", "Mobile", "Tablet",
        "Laptop", "Mobile", "Tablet",
        "Laptop", "Mobile", "Tablet"
    ],
    "Region": [
        "East", "West", "North",
        "South", "East", "West",
        "North", "South", "East",
        "West", "North", "South",
        "East", "West", "North"
    ],
    "Sales": [
        50000, 30000, 20000,
        55000, 32000, 22000,
        60000, 35000, 25000,
        58000, 37000, 24000,
        62000, 39000, 26000
    ],
    "Units": [
        5, 10, 8,
        6, 11, 9,
        7, 12, 10,
        6, 13, 9,
        8, 14, 11
    ],
    "Rep": [
        "John", "Alice", "Bob",
        "John", "Alice", "Bob",
        "John", "Alice", "Bob",
        "John", "Alice", "Bob",
        "John", "Alice", "Bob"
    ]
}
df = pd.DataFrame(data)

In [5]:
df

          Date Product Region  Sales  Units    Rep
0   2026-01-05  Laptop   East  50000      5   John
1   2026-01-12  Mobile   West  30000     10  Alice
2   2026-01-18  Tablet  North  20000      8    Bob
3   2026-02-03  Laptop  South  55000      6   John
4   2026-02-10  Mobile   East  32000     11  Alice
5   2026-02-17  Tablet   West  22000      9    Bob
6   2026-03-02  Laptop  North  60000      7   John
7   2026-03-09  Mobile  South  35000     12  Alice
8   2026-03-16  Tablet   East  25000     10    Bob
9   2026-04-04  Laptop   West  58000      6   John
10  2026-04-11  Mobile  North  37000     13  Alice
11  2026-04-18  Tablet  South  24000      9    Bob
12  2026-05-06  Laptop   East  62000      8   John
13  2026-05-13  Mobile   West  39000     14  Alice
14  2026-05-20  Tablet  North  26000     11    Bob

In [8]:
pd.pivot_table(df, values='Sales', index='Region', columns='Product')

Product   Laptop   Mobile   Tablet
Region
East     56000.0  32000.0  25000.0
North    60000.0  37000.0  23000.0
South    55000.0  35000.0  24000.0
West     58000.0  34500.0  22000.0

In [12]:
pd.pivot_table(df, values='Sales', index='Region', columns='Product', aggfunc='median')

Product   Laptop   Mobile   Tablet
Region
East     56000.0  32000.0  25000.0
North    60000.0  37000.0  23000.0
South    55000.0  35000.0  24000.0
West     58000.0  34500.0  22000.0

In [15]:
# Multiple vales
pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product')

           Sales                    Units
Product   Laptop   Mobile   Tablet Laptop Mobile Tablet
Region
East     56000.0  32000.0  25000.0    6.5   11.0   10.0
North    60000.0  37000.0  23000.0    7.0   13.0    9.5
South    55000.0  35000.0  24000.0    6.0   12.0    9.0
West     58000.0  34500.0  22000.0    6.0   12.0    9.0

In [14]:
# Cross Tabs(Count)
pd.crosstab(df['Region'], df['Product'])

Product  Laptop  Mobile  Tablet
Region
East          2       1       1
North         1       1       2
South         1       1       1
West          1       2       1